### ISSUE TITLE
Opennebula 5 support

### ISSUE THREAD

**Issue by a-nldisr** [OpenNebula/addon-appmarket#56]
Currently the page states that the following versions are supported:

AppMarket Version	OpenNebula Version
2.1.0	4.14.2
<= 2.0.3	4.10, 4.12

Are there any plans to support Opennebula 5?

**Comment by jfontan** [comment]
OpenNebula 5 comes with an integrated Marketplace and most probably we are going to deprecate this project. Do you find it lacking in any feature?

http://docs.opennebula.org/5.2/advanced_components/marketplace/market_http.html
